stages:
  - begin
  - stop

begin:
  tags:
    - docker-socket-binding
  stage: begin
  when: manual
  script:
    - docker-compose up -d

stop:
  tags:
    - docker-socket-binding
  stage: stop
  when: manual
  script:
    - docker-compose down
