stages:
  - begin
  - stop

begin:
  tags:
    - docker-socket-binding
  stage: begin
  when: manual
  variables:
    COMPOSE_ENV_FILES: $ENV_FILE
  # before_script:
  #   - echo $ENV_FILE > .env
  script:
    # - docker-compose up -d
    - docker-compose config --environment

stop:
  tags:
    - docker-socket-binding
  stage: stop
  when: manual
  script:
    - docker-compose down
