stages:
  - begin
  - stop

begin:
  tags:
    - docker-socket-binding
  stage: begin
  when: manual
  # variables:
  #   COMPOSE_ENV_FILES: $COMPOSE_ENV_FILES
  before_script:
    - echo $COMPOSE_ENV_FILES
    - echo $ENV_FILE
  #   - echo $ENV_FILE > .env
  script:
    # - docker-compose up -d
    - docker-compose config --environment

stop:
  tags:
    - docker-socket-binding
  stage: stop
  when: manual
  script:
    - docker-compose down
